#!/usr/bin/env bash

<<comment
  @Author: João Gabriel Souza Gois
  @Description:
    - It compiles based on source code filename informed as first argument of the script,
    ensures it will use cs50 lib in the process, then execute it and finally, after execution,
    it removes the (executable) binary.
  @Details:
    - It handles 2 different executable calls, with or without arguments. 
comment

compile() (
  # To make keyboard interrupt be able to
  # interrupt only 'compile' if it is running
  trap - INT
  
  source_file="$_dirname/$filename"
  gcc $source_file -o .binary -lm -lcs50
)

run() (
  # To make keyboard interrupt be able to
  # interrupt only 'run' if it is running
  trap - INT

  if [[ $args == "" ]]; then
    $_dirname/.binary
  else
    $_dirname/.binary $args
  fi
)

main() {
  # To avoid keyboard interrupt to stop whole script
  trap '' INT
  _dirname="$(pwd)"
  filename=$1
  args=""
  # Filling args if any
  for arg in "$@"; do
    if [[ $arg != $1 ]]; then
      args="${args} $arg";
    fi
  done

  compile
  run
  [ -e "$_dirname/.binary" ] && rm $_dirname/.binary
}

main $@
