#!/bin/bash

# if your are using clang change to "make filter" (As I use in CS50's codespaces)
make filter_gcc

./filter -r images/courtyard.bmp images/courtyard-outputs/courtyard_reflected.bmp
./filter -g images/courtyard.bmp images/courtyard-outputs/courtyard_grayscale.bmp
./filter -e images/courtyard.bmp images/courtyard-outputs/courtyard_edges.bmp
./filter -b images/courtyard.bmp images/courtyard-outputs/courtyard_blur.bmp

./filter -r images/stadium.bmp images/stadium-outputs/stadium_reflected.bmp
./filter -g images/stadium.bmp images/stadium-outputs/stadium_grayscale.bmp
./filter -e images/stadium.bmp images/stadium-outputs/stadium_edges.bmp
./filter -b images/stadium.bmp images/stadium-outputs/stadium_blur.bmp

./filter -r images/tower.bmp images/tower-outputs/tower_reflected.bmp
./filter -g images/tower.bmp images/tower-outputs/tower_grayscale.bmp
./filter -e images/tower.bmp images/tower-outputs/tower_edges.bmp    
./filter -b images/tower.bmp images/tower-outputs/tower_blur.bmp 

./filter -r images/yard.bmp images/yard-outputs/yard_reflected.bmp
./filter -g images/yard.bmp images/yard-outputs/yard_grayscale.bmp
./filter -e images/yard.bmp images/yard-outputs/yard_edges.bmp
./filter -b images/yard.bmp images/yard-outputs/yard_blur.bmp
