#!/usr/bin/env bash

main() {
  source venv/bin/activate &> /dev/null
  if [ $? != 0 ]; then
    python3 -m venv venv
    source venv/bin/activate
    pip3 install Flask Flask-Session cs50
  fi
  flask run
}

main
